---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR to Tomcat
      copy:
        src: "/var/snap/jenkins/4865/workspace/Maven-Ansible/target/MavenAnsibleApp.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleApp.war"
        remote_src: no
        
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
